---
# tasks file for role-zsh
- name: Update cache if on Debian or Ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  become: yes

- name: Register who the user executing this role is
  command:
    cmd: "whoami"
  register: whoami
  changed_when: false

- name: Make sure that the shadow package is installed (for usermod, Alpine)
  package:
    name: shadow
    state: present
  become: true
  when: ansible_facts['os_family'] == "Alpine"

- name: Include tasks for ZSH
  include_tasks: zsh.yml
  when: install_zsh is defined and install_zsh

- name: Include tasks for bash
  include_tasks: bash.yml
  when: install_bash is defined and install_bash
