---
# tasks file for role-zsh
- name: Update cache if on Debian or Ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  become: yes

- name: Install a list of packages
  package:
    name: "{{ terminal_packages }}"
    state: present
  become: yes

- name: Install oh-my-zsh
  shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    creates: "$HOME/.oh-my-zsh"

- name: Install p10k (manually)
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: "1"
    dest: '$HOME/powerlevel10k'

- name: Copy p10k configuration
  copy:
    src: templates/ZSH/p10k.zsh
    dest: "$HOME/.p10k.zsh"
  ignore_errors: true
  register: global_config

- name: Copy p10k configuration (if global config failes)
  copy:
    src: templates/ZSH/p10k.zsh
    dest: "$HOME/.p10k.zsh"
  ignore_errors: true
  when: global_config.failed

- name: Copy ZSH configuration
  copy:
    src: "../../../config_files/ZSH/zshrc"
    dest: "$HOME/.zshrc"
  ignore_errors: true
  register: global_config

- name: Copy ZSH configuration (if global config fails)
  copy:
    src: templates/ZSH/zshrc
    dest: "$HOME/.zshrc"
  when: global_config.failed

- name: Register who the user executing this role is
  command:
    cmd: "whoami"
  register: whoami
  changed_when: false

- name: Make sure that the shadow package is installed (for usermod, Alpine)
  package:
    name: shadow
    state: present
  become: true
  when: ansible_facts['os_family'] == "Alpine"

- name: Change default shell to ZSH
  command:
    cmd: 'usermod --shell /bin/zsh "{{ whoami.stdout }}"'
  changed_when: false
  become: true

- name: Create a directory for zsh-syntax-highlighting if it does not exist
  file:
    path: "$HOME/Programs/zsh-syntax-highlighting"
    state: directory

- name: Clone the syntax highlighting plugin locally
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "$HOME/zsh-syntax-highlighting/"

- name: Reload the ZSH configuration
  shell: "source $HOME/.zshrc"
  args:
    executable: "/bin/zsh"
  changed_when: false
