---
- name: Install a list of packages
  package:
    name: "{{ zsh_packages }}"
    state: present
  become: true

- name: Install oh-my-zsh
  shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    creates: "$HOME/.oh-my-zsh"

- name: Install p10k (manually)
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: "1"
    dest: '$HOME/powerlevel10k'

- name: Copy p10k configuration
  copy:
    src: templates/ZSH/p10k.zsh
    dest: "$HOME/.p10k.zsh"
  ignore_errors: true
  register: global_config

- name: Copy p10k configuration (if global config failes)
  copy:
    src: templates/ZSH/p10k.zsh
    dest: "$HOME/.p10k.zsh"
  ignore_errors: true
  when: global_config.failed

- name: Copy ZSH configuration
  copy:
    src: "../../../config_files/ZSH/zshrc"
    dest: "$HOME/.zshrc"
  ignore_errors: true
  register: global_config

- name: Copy ZSH configuration (if global config fails)
  copy:
    src: templates/ZSH/zshrc
    dest: "$HOME/.zshrc"
  when: global_config.failed

- name: Change default shell to ZSH
  command:
    cmd: 'usermod --shell /bin/zsh "{{ whoami.stdout }}"'
  changed_when: false
  become: true

- name: Create a directory for zsh-syntax-highlighting if it does not exist
  file:
    path: "$HOME/Programs/zsh-syntax-highlighting"
    state: directory

- name: Clone the syntax highlighting plugin locally
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "$HOME/zsh-syntax-highlighting/"

- name: Reload the ZSH configuration
  shell: "source $HOME/.zshrc"
  args:
    executable: "/bin/zsh"
  changed_when: false
