### THIS FILE IS MANAGED BY ANSIBLE

# Enable Powerlevel10k instant prompt.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# PATH
export PATH=$HOME/.cargo/bin/:$PATH

# fzf command (primarily for neovim)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*"'
export FZF_DEFAULT_OPTS='--bind J:down,K:up --ansi'

# Don't autocorrect commands
unsetopt correct_all

# Wayland + virt-viewer fix
xhost + &> /dev/null

# Kill autocorrection
DISABLE_CORRECTION="true"

# Mozilla programs enable Wayland
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1

# Export kubeconfig
export KUBECONFIG=~/.kube/config

autoload -U compinit
compinit

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export EDITOR="nvim"

# Command auto-correction.
ENABLE_CORRECTION="true"

# ZSH plugins
plugins=(git rsync colored-man-pages kubectl)

source $ZSH/oh-my-zsh.sh

# Source zsh with the zshreload command
alias zshreload="source ~/.zshrc"
# Download best quality of audio and video in mp4 joined format for a URL
alias ytdlbestmp4="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"
# History view
alias h="history -20"
# All vims are neovim
alias vim='nvim'
alias v='nvim'
# Change dir on exit ranger
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias r='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
# Make nautilus open in the current dir
alias nautilus='nautilus -w $(pwd)'
# Khal alias
alias worknew='khal new -a work'
alias ownnew='khal new -a personal'
alias randompass='< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
